config/routes.rb
Rails.application.routes.draw do
    root "posts#index"

    get "login", to: "sessions#new"
    post "login", to: "sessions#create"

    get "users/new", to: "users#new", as: "register"
    post "users/create"

    get "users/lost_password", as: "lost_password"
    post "users/lost_password", as: "send_lost_password"

    get "users/show/:id", to: "users#show", as: "profile"
    get "users/edit/:id", to: "users#edit", as: "profile/edit"
    put "users/update/:id", to: "users#update", as: "profile/update"

    get "new_post", to: "posts#new"
    post "new_post", to: "posts#create"

    get "my_posts", to: "posts#my_posts"

    delete "logout", to: "sessions#destroy"
    
    resources :posts
    resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    belongs_to :user

    validates :petname, presence: true
    validates :age, presence: true
    validates :description, presence: true
    validates :species, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts

    validates :email, presence: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
  end

  def new
    if session[:user_id]
      @post = Post.new
    else
      redirect_to root_path, notice: "Ehhez a művelethez be kell jelentkezni!"
    end

  end

  def create
    if session[:user_id]
      @post = Post.new(post_params)
      if @post.save
        redirect_to root_path, notice: "Sikeres poszt létrehozás!"
      else
        render :'posts/new'
      end

    else
      redirect_to root_path, notice: "Ehhez a művelethez be kell jelentkezni!"
    end

  end

  def my_posts
    if session[:user_id]
      @posts = Post.where(user_id: session[:user_id])
    else
      redirect_to root_path, notice: "Ehhez a művelethez be kell jelentkezni!"
    end
  end

  def edit
    if session[:user_id] && session[:user_id] == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
    else
      redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
    end

  end

  def update
    if session[:user_id] && session[:user_id] == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])

      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    else
      redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
    end
  end

  def destroy
    if session[:user_id] && session[:user_id] == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to my_posts_path
    else
      redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
    end
  end

  private
  def post_params
    if session[:user_id]
      params.require(:post).permit(:petname, :age, :description, :species, :image).merge(user_id: session[:user_id])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Sikeres bejelentkezés!"
        else
            flash.now[:alert] = "Hibás bejelentkezési adatok!"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Sikeres kijelentkezés"
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def show
        if session[:user_id] && session[:user_id] == User.find(params[:id]).id
            @user = User.find(session[:user_id])
        else
            redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
        end

    end

    def edit
        if session[:user_id] && session[:user_id] == User.find(params[:id]).id
            @user = User.find(params[:id])
        else
            redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
        end
    end

    def update
        if session[:user_id]
            @user = User.find(params[:id])

            if @user.update(user_edit_params)
                redirect_to @user
            else
                render :edit
            end
        else
            redirect_to root_path, notice: "Ehhez a művelethez nincs jogosultságod!"
        end
    end

    def create

        if User.exists?(user_params[:email])
            redirect_to register_path, alert: "Már regisztráltak ezzel az e-maillel!"
        else
            @user = User.new(user_params)
            if @user.save
                # session cookie beállítás, innen lehet nézni hogy be van e jelentkezve
                # session[:user_id] = @user.id
                redirect_to login_path, notice: "Sikeres regisztráció!"
            else
                render :'users/new'
            end
        end
    end

    def lost_password
        user = User.find_by(email: params[:email])
        if user.present?
            puts(user[:password_digest])
            redirect_to login_path, notice: "A jelszó hash a terminálon van!"
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

    def user_edit_params
        params.require(:user).permit(:email, :name)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hazi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
    <%= form_with model: @post do |form| %>

      <%= render partial: "shared/flash" %>

      <div class="mb-3">
        <%= form.label :petname, "Kedvenc neve" %>
        <%= form.text_field :petname, class: "form-control", placeholder: "Név", :required => true %>
      </div>

      <div class="mb-3">
        <%= form.label :age, "Kedvenc kora" %>
        <%= form.text_field :age, class: "form-control", placeholder: "Kor", :required => true %>
      </div>

      <div class="mb-3">
        <%= form.label :species, "Kedvenc fajtája" %>
        <%= form.text_field :species, class: "form-control", placeholder: "Kaméleon, border collie, stb.", :required => true %>
      </div>

      <div class="mb-3">
        <%= form.label :description, "Leírás" %>
        <%= form.text_field :description, class: "form-control", placeholder: "Bármi ami eszedbe jut az állatkádról...", :required => true %>
      </div>


      <div class="mb-3">
        <%= form.label :image, "Kép" %>
        <%= form.file_field :image, :required => true %>
      </div>

      <div class="mb-3">
        <%= form.submit "Beküldöm!", class: "btn btn-primary" %>
        <%= link_to "Mégse", root_path, :class => "btn btn-link", :required => true %>
      </div>

    <% end %>

app/views/posts/edit.html.erb
<div class="row m-0">
  <div class="container col-md-3 pt-5">
    <h1 class="h3 mb-3 font-weight-normal">Poszt szerkesztése</h1>
  <%= render "form", post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<main role="main">
  <div class="album py-5">
    <div class="container">

      <%= render partial: "shared/flash" %>

      <h1 class="mb-3">Főoldal</h1>
      <div class="row">

        <% @posts.each do |post| %>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">

                <%= image_tag(post.image, class: "card-img-top", style: "height: 225px; width: 100%; display: block;") %>

              <!--<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_178fa3d88e2%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_178fa3d88e2%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.70000076293945%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">-->
              <div class="card-body">
                <p class="card-text"><%= post.petname %></p>
                <p class="card-text"><%= post.species %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to "View", post, :class => "btn btn-sm btn-outline-secondary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<svg xmlns="http://www.w3.org/2000/svg" width="348" height="225" viewBox="0 0 348 225" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="17" style="font-weight:bold;font-size:17pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text></svg>

app/views/posts/my_posts.html.erb
<main role="main">
  <div class="album py-5">
    <div class="container">

      <%= render partial: "shared/flash" %>
      <h3 class="mb-2">Saját posztjaim</h3>
      <div class="row">

        <div class="col-md-12">
          <table class="table table-striped table-bordered">
            <tr>
              <th>
                Kedvenc neve
              </th>
              <th>
                Kedvenc kora
              </th>
              <th>
                Kedvenc fajtája
              </th>
              <th>
                Kedvenc leírása
              </th>
              <th>
                Műveletek
              </th>
            </tr>

            <% @posts.each do |post| %>
              <tr>
                <td>
                  <%= post.petname %>
                </td>
                <td>
                  <%= post.age %>
                </td>
                <td>
                  <%= post.species %>
                </td>
                <td>
                  <%= post.description %>
                </td>
                <td>
                  <%= link_to "Megnézem", post_path(post.id) %>
                  <%= link_to "Szerkesztés", edit_post_path(post.id) %>
                  <%= button_to "Törlés", post_path(post.id), method: :delete, class: "btn btn-link p-0 m-0" %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

</main>

<svg xmlns="http://www.w3.org/2000/svg" width="348" height="225" viewBox="0 0 348 225" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="17" style="font-weight:bold;font-size:17pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text></svg>

app/views/posts/new.html.erb
<div class="row m-0">
  <div class="container col-md-3 pt-5">
    <h1 class="h3 mb-3 font-weight-normal">Új poszt létrehozása</h1>
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<main role="main">
  <div class="container">
    <div class="m-4">

      <%= image_tag(@post.image, style: "width: 50%", class: "mb-3") %>

      <table class="table table-striped">
        <tbody>
        <tr>
          <th scope="row">Kedvenc gazdája:</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row">Kedvenc neve:</th>
          <td><%= @post.petname %></td>
        </tr>
        <tr>
          <th scope="row">Kedvenc kora:</th>
          <td><%= @post.age %></td>
        </tr>
        <tr>
          <th scope="row">Fajtája:</th>
          <td><%= @post.species %></td>
        </tr>
        <tr>
          <th scope="row">Leírás:</th>
          <td><%= @post.description %></td>
        </tr>
        </tbody>
      </table>
    </div>

  </div>
</main>

app/views/shared/_flash.html.erb
<% if flash[:notice]  %>
<div class="alert alert-info mt-4" role="alert">
  <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
  <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container d-flex justify-content-between">
      <strong><%= link_to "Pet showroom", "/", :class => "navbar-brand d-flex align-items-center" %></strong>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <% unless session[:user_id] %>
            <li class="nav-item">
              <%=  link_to "Bejelentkezés", login_path, :class => "nav-link d-flex" %>
            </li>
          <% end %>

          <% if session[:user_id] %>
            <li class="nav-item">
              <%=  button_to "Kijelentkezés", logout_path, method: :delete, :class => "btn btn-link nav-link d-flex" %>
            </li>
            <li class="nav-item">
              <%=  link_to "Új poszt", new_post_path, :class => "nav-link d-flex" %>
            </li>
            <li class="nav-item">
              <%=  link_to "Az én kedvenceim", my_posts_path, :class => "nav-link d-flex" %>
            </li>
            <li class="nav-item">
              <%=  link_to "Profilom", profile_path(session[:user_id]), :class => "nav-link d-flex" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/users/_form.html.erb
    <%= form_with model: @user do |form| %>

      <%= render partial: "shared/flash" %>

      <div class="mb-3">
        <%= form.label :name, "Gazda neve" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Név", :required => true %>
      </div>

      <div class="mb-3">
        <%= form.label :email, "Gazda emailje" %>
        <%= form.text_field :email, class: "form-control", placeholder: "E-mail", :required => true %>
      </div>

      <div class="mb-3">
        <%= form.submit "Változtatások mentése", class: "btn btn-primary" %>
        <%= link_to "Mégse", profile_path(session[:user_id]), :class => "btn btn-link", :required => true %>
      </div>

    <% end %>

app/views/users/edit.html.erb
<div class="row m-0">
  <div class="container col-md-3 pt-5">
    <h1 class="h3 mb-3 font-weight-normal">Profil szerkesztése</h1>
  <%= render "form", post: @user %>
  </div>
</div>

app/views/users/lost_password.html.erb
<div class="row m-0">
  <div class="container col-md-3">
    <div class="pt-3">
      <%= form_with model: @user do |form| %>

        <%= render partial: "shared/flash" %>

        <div class="mb-3">
          <%= form.label :email, "E-mail" %>
          <%= form.email_field :email, class: "form-control", placeholder: "Név", :required => true %>
        </div>

        <!--
        <div class="mb-3">
          <%= form.label :password, "Új jelszó" %>
          <%= form.password_field :password, class: "form-control"%>
        </div>
        <div class="mb-3">
          <%= form.label :password_confirmation , "Új jelszó jelszó megerősítése"%>
          <%= form.password_field :password_confirmation, class: "form-control"%>
        </div>-->

        <div class="mb-3">
          <%= form.submit "Kérem a jelszavam!", class: "btn btn-primary" %>
          <%= link_to "Vissza", login_path, :class => "btn btn-link" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <p><br/></p>
  <div class="py-5 text-center">
    <h2>Regisztráció</h2>
  </div>
  <div class="row">
    <div class="container">
      <%= form_with model: @user, url: users_create_path do |form| %>

        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :email %>
          <%= form.text_field :email, class: "form-control", placeholder: "arvizturo@tukorfurogep.com" %>
        </div>

        <div class="mb-3">
          <%= form.label :name, "Teljes név" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Gipsz Jakab" %>
        </div>

        <div class="mb-3">
          <%= form.label :password, "Jelszó" %>
          <%= form.password_field :password, class: "form-control"%>
        </div>
        <div class="mb-3">
          <%= form.label :password_confirmation , "Jelszó megerősítése"%>
          <%= form.password_field :password_confirmation, class: "form-control"%>
        </div>

        <div class="mb-3">
          <%= form.submit "Regisztrálok", class: "btn btn-primary" %>
          <%= link_to "Vissza", login_path, :class => "btn btn-link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<main role="main">
  <div class="container">
    <div class="m-4">
      <h2>Profil</h2>
      <table class="table table-striped">
        <tbody>
          <tr>
            <th scope="row">Gazda neve:</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th scope="row">Gazda email címe:</th>
            <td><%= @user.email %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to "Profil szerkesztése", profile_edit_path(session[:user_id]), :class => "btn btn-outline-primary" %>
    </div>
  </div>
</main>